# Generated by Django 2.2.9 on 2021-08-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanilhaSituacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(editable=False, help_text='Deve-se importar um arquivo no formato .xls com duas colunas. Sendo CD_CPF_RESPONSAVEL e MSG', upload_to='situacao_cadastro/planilhas', verbose_name='Planilha')),
                ('data_corte_planilha', models.DateField(verbose_name='Data de corte da planilha')),
                ('data_corte_lote', models.DateField(verbose_name='Data de corte do lote')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('extraido', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name': 'Planilha de Situação Cadastral',
                'verbose_name_plural': 'Planilhas de Situações Cadastrais',
            },
        ),
    ]
