# Generated by Django 2.2.9 on 2021-08-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilhasituacao',
            name='arquivo',
            field=models.FileField(help_text='Deve-se importar um arquivo no formato <strong>.xls</strong> com duas colunas. Sendo <strong>CD_CPF_RESPONSAVEL e MSG</strong>', upload_to='situacao_cadastro/planilhas', verbose_name='Planilha'),
        ),
    ]
