# Generated by Django 2.2.9 on 2021-01-22 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200818_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Log e-mail enviado (Atualização Cadastral)', 'verbose_name_plural': 'Log e-mails enviados (Atualização Cadastral)'},
        ),
    ]
